### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by awesemo** [rzproject/cms-sandbox#1]
Receiving this error message when ever I execute console command:
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
You have requested a non-existent parameter "session_name".

**Comment by awesemo** [comment]
Resolved.
config.yml

change from:

```
framework:
    session:
        name: %session_name%
        cookie_lifetime: %cookie_lifetime%
```

to:

```
framework:
    session: ~
```
